// Wheelwise Car Database
// 20 highly curated vehicles ranging from budget commuters to ultra-luxury EVs

const CARS_DATABASE = [
  {
    id: "toyota-corolla",
    name: "Toyota Corolla Hybrid",
    brand: "Toyota",
    price: 23500,
    type: "sedan",
    fuel: "hybrid",
    lifestyle: "commute",
    priority: "economy",
    specs: {
      range: "53 MPG City / 46 MPG Hwy",
      acceleration: "9.0s",
      horsepower: "138 hp",
      safety: "Top Safety Pick+",
      seats: 5,
      cargo: "13.1 cu ft"
    },
    description: "The absolute benchmark of reliable, ultra-efficient daily commuting with premium hybrid savings and low cost of ownership.",
    whyMatch: "Its hybrid powertrain offers class-leading economy, perfect for your budget-conscious daily commutes.",
    badge: "Reliability King",
    color: "#4FC3F7"
  },
  {
    id: "honda-civic",
    name: "Honda Civic Hatchback",
    brand: "Honda",
    price: 24900,
    type: "hatchback",
    fuel: "gasoline",
    lifestyle: "commute",
    priority: "economy",
    specs: {
      range: "31 MPG City / 39 MPG Hwy",
      acceleration: "7.7s",
      horsepower: "158 hp",
      safety: "5-Star Overall Rating",
      seats: 5,
      cargo: "24.5 cu ft"
    },
    description: "Sporty, versatile, and highly practical. The benchmark for styling and cabin space in a compact hatchback.",
    whyMatch: "Combines athletic driving dynamics with hatchback versatility, providing high mileage without sacrificing fun.",
    badge: "Versatile Standard",
    color: "#29B6F6"
  },
  {
    id: "hyundai-kona",
    name: "Hyundai Kona Tech Edition",
    brand: "Hyundai",
    price: 24250,
    type: "suv",
    fuel: "gasoline",
    lifestyle: "commute",
    priority: "tech",
    specs: {
      range: "29 MPG City / 34 MPG Hwy",
      acceleration: "8.8s",
      horsepower: "147 hp",
      safety: "Top Safety Pick",
      seats: 5,
      cargo: "25.5 cu ft"
    },
    description: "A compact urban SUV packed with high-tech features including dual 12.3-inch displays and wireless connectivity.",
    whyMatch: "Gets you top-tier driving assist features and immersive dual-screens at an extremely accessible budget.",
    badge: "Tech Bargain",
    color: "#AB47BC"
  },
  {
    id: "mazda-3",
    name: "Mazda 3 Premium Hatch",
    brand: "Mazda",
    price: 25690,
    type: "hatchback",
    fuel: "gasoline",
    lifestyle: "commute",
    priority: "luxury",
    specs: {
      range: "26 MPG City / 33 MPG Hwy",
      acceleration: "6.9s",
      horsepower: "191 hp",
      safety: "Top Safety Pick+",
      seats: 5,
      cargo: "20.1 cu ft"
    },
    description: "A premium Japanese hatchback featuring near-luxury cabin finishes, high-grade leather, and organic steering feedback.",
    whyMatch: "Delivers an executive interior design and near-luxury cabin quietness at a standard budget cost.",
    badge: "Bargain Luxury",
    color: "#EC407A"
  },
  {
    id: "subaru-outback",
    name: "Subaru Outback Wilderness",
    brand: "Subaru",
    price: 28895,
    type: "wagon",
    fuel: "gasoline",
    lifestyle: "adventure",
    priority: "tech",
    specs: {
      range: "26 MPG City / 32 MPG Hwy",
      acceleration: "8.6s",
      horsepower: "182 hp",
      safety: "Top Safety Pick+",
      seats: 5,
      cargo: "32.6 cu ft"
    },
    description: "The quintessential rugged wagon. Equipped with standard Symmetrical All-Wheel Drive and generous ground clearance.",
    whyMatch: "Perfect for active off-road lifestyles with durable interior materials and reliable standard active safety features.",
    badge: "Off-Road Ready",
    color: "#66BB6A"
  },
  {
    id: "ford-mustang",
    name: "Ford Mustang GT Fastback",
    brand: "Ford",
    price: 42495,
    type: "sports",
    fuel: "gasoline",
    lifestyle: "speed",
    priority: "performance",
    specs: {
      range: "15 MPG City / 24 MPG Hwy",
      acceleration: "4.3s",
      horsepower: "480 hp",
      safety: "5-Star Rating",
      seats: 4,
      cargo: "13.3 cu ft"
    },
    description: "A legendary American muscle icon boasting a heavy-rumbling V8 engine and raw performance capabilities.",
    whyMatch: "Feeds your desire for track speed with an authentic, high-horsepower naturally aspirated V8 muscle experience.",
    badge: "V8 Pure Power",
    color: "#FF7043"
  },
  {
    id: "tesla-model-3",
    name: "Tesla Model 3 Long Range",
    brand: "Tesla",
    price: 38990,
    type: "sedan",
    fuel: "electric",
    lifestyle: "eco",
    priority: "tech",
    specs: {
      range: "341 miles (EPA)",
      acceleration: "4.2s",
      horsepower: "340 hp",
      safety: "5-Star Overall NHTSA",
      seats: 5,
      cargo: "21.0 cu ft"
    },
    description: "The global benchmark in modern electric vehicles. Unmatched minimalist cabin tech and Tesla Autopilot safety suite.",
    whyMatch: "Unbeatable smart tech, high-efficiency electric mileage, and zero-carbon daily driving with high performance.",
    badge: "EV Tech Benchmark",
    color: "#26C6DA"
  },
  {
    id: "toyota-rav4",
    name: "Toyota RAV4 Hybrid XSE",
    brand: "Toyota",
    price: 31725,
    type: "suv",
    fuel: "hybrid",
    lifestyle: "family",
    priority: "economy",
    specs: {
      range: "41 MPG City / 38 MPG Hwy",
      acceleration: "7.3s",
      horsepower: "219 hp",
      safety: "Top Safety Pick",
      seats: 5,
      cargo: "37.6 cu ft"
    },
    description: "A family crossover staple that blends an expansive passenger cabin with top-tier hybrid economy.",
    whyMatch: "Provides maximum utility and cargo space for your family trips while keeping fuel bills exceptionally low.",
    badge: "Family Favorite",
    color: "#26A69A"
  },
  {
    id: "kia-ev6",
    name: "Kia EV6 GT-Line",
    brand: "Kia",
    price: 42600,
    type: "suv",
    fuel: "electric",
    lifestyle: "eco",
    priority: "tech",
    specs: {
      range: "310 miles (EPA)",
      acceleration: "5.1s",
      horsepower: "320 hp",
      safety: "Top Safety Pick+",
      seats: 5,
      cargo: "24.4 cu ft"
    },
    description: "Futuristic design meets super-fast charging. The 800V charging structure refills 10% to 80% battery in 18 minutes.",
    whyMatch: "Combines highly premium space, head-turning futuristic styling, and top-tier electric range.",
    badge: "Futuristic Design",
    color: "#7E57C2"
  },
  {
    id: "genesis-gv70",
    name: "Genesis GV70 2.5T Sport",
    brand: "Genesis",
    price: 45150,
    type: "suv",
    fuel: "gasoline",
    lifestyle: "family",
    priority: "luxury",
    specs: {
      range: "22 MPG City / 28 MPG Hwy",
      acceleration: "6.0s",
      horsepower: "300 hp",
      safety: "Top Safety Pick+",
      seats: 5,
      cargo: "28.9 cu ft"
    },
    description: "An incredibly elegant luxury SUV that offers bespoke cabin styling and high-tier materials that rival German flagships.",
    whyMatch: "Delivers absolute luxury, top-grade quiet comfort, and standard elite warranty safety for your family.",
    badge: "Ultra Premium Value",
    color: "#EC407A"
  },
  {
    id: "jeep-wrangler",
    name: "Jeep Wrangler 4xe Hybrid",
    brand: "Jeep",
    price: 50695,
    type: "suv",
    fuel: "hybrid",
    lifestyle: "adventure",
    priority: "performance",
    specs: {
      range: "49 MPGe / 21 mi Electric",
      acceleration: "6.0s",
      horsepower: "375 hp",
      safety: "4-Star Frontal",
      seats: 5,
      cargo: "31.7 cu ft"
    },
    description: "A trail-rated off-road legend boosted by a plug-in hybrid motor. Take off the doors and cruise trails silently.",
    whyMatch: "Satisfies your heavy adventure drive with plug-in hybrid efficiency and massive climbing power.",
    badge: "Hybrid Adventurer",
    color: "#9CCC65"
  },
  {
    id: "bmw-i4",
    name: "BMW i4 eDrive40 Gran Coupe",
    brand: "BMW",
    price: 57300,
    type: "sedan",
    fuel: "electric",
    lifestyle: "speed",
    priority: "performance",
    specs: {
      range: "307 miles (EPA)",
      acceleration: "4.7s",
      horsepower: "335 hp",
      safety: "Top-Tier Premium",
      seats: 5,
      cargo: "10.0 cu ft"
    },
    description: "Translates BMW's legendary dynamic handling directly into an elite luxury electric sedan.",
    whyMatch: "Combines zero-emission driving with BMW's responsive sports chassis, precision steering, and upscale interior tech.",
    badge: "Electric Athlete",
    color: "#29B6F6"
  },
  {
    id: "porsche-macan",
    name: "Porsche Macan S",
    brand: "Porsche",
    price: 72300,
    type: "suv",
    fuel: "gasoline",
    lifestyle: "speed",
    priority: "performance",
    specs: {
      range: "17 MPG City / 23 MPG Hwy",
      acceleration: "4.4s",
      horsepower: "375 hp",
      safety: "5-Star Equivalent",
      seats: 5,
      cargo: "17.2 cu ft"
    },
    description: "The absolute handling benchmark for sport utility vehicles. Steers and brakes with iconic Porsche pedigree.",
    whyMatch: "Delivers sports-car track metrics inside a highly practical, luxurious luxury SUV format.",
    badge: "Track Bred SUV",
    color: "#EF5350"
  },
  {
    id: "chevrolet-corvette",
    name: "Chevrolet Corvette Stingray C8",
    brand: "Chevrolet",
    price: 68300,
    type: "sports",
    fuel: "gasoline",
    lifestyle: "speed",
    priority: "performance",
    specs: {
      range: "16 MPG City / 25 MPG Hwy",
      acceleration: "2.9s",
      horsepower: "495 hp",
      safety: "Untested (Supercar)",
      seats: 2,
      cargo: "12.6 cu ft"
    },
    description: "A mid-engine aerodynamic supercar masterpiece, dealing 0-60 times under 3 seconds for a fraction of exotic car costs.",
    whyMatch: "For the absolute speed enthusiast seeking extreme track acceleration and high-g turn capabilities.",
    badge: "Supercar Bargain",
    color: "#FF7043"
  },
  {
    id: "porsche-911",
    name: "Porsche 911 Carrera",
    brand: "Porsche",
    price: 114400,
    type: "sports",
    fuel: "gasoline",
    lifestyle: "speed",
    priority: "performance",
    specs: {
      range: "18 MPG City / 24 MPG Hwy",
      acceleration: "3.8s",
      horsepower: "379 hp",
      safety: "World Class Elite",
      seats: 4,
      cargo: "4.6 cu ft"
    },
    description: "The legendary gold standard of sports cars. Impeccable balance, flat-six rear engine layout, and perfect engineering.",
    whyMatch: "The ultimate driving purist's dream. Delivers standard-setting handling, premium prestige, and classic lines.",
    badge: "Automotive Icon",
    color: "#EF5350"
  },
  {
    id: "tesla-model-s",
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    price: 89990,
    type: "sedan",
    fuel: "electric",
    lifestyle: "eco",
    priority: "performance",
    specs: {
      range: "359 miles (EPA)",
      acceleration: "1.99s",
      horsepower: "1020 hp",
      safety: "5-Star NHTSA Perfect",
      seats: 5,
      cargo: "25.0 cu ft"
    },
    description: "The fastest accelerating production sedan on Earth. Boasts three high-output electric motors producing over 1,000 HP.",
    whyMatch: "If you want mind-bending electric speed (0-60 in 1.99s) and futuristic tech controls in a premium sedan.",
    badge: "Speed Overlord",
    color: "#26C6DA"
  },
  {
    id: "range-rover",
    name: "Range Rover Autobiography LWB",
    brand: "Land Rover",
    price: 141100,
    type: "suv",
    fuel: "hybrid",
    lifestyle: "family",
    priority: "luxury",
    specs: {
      range: "21 MPG Comb / 51 mi EV",
      acceleration: "5.2s",
      horsepower: "523 hp",
      safety: "Elite Premium Guard",
      seats: 5,
      cargo: "40.7 cu ft"
    },
    description: "The pinnacle of executive luxury travel. Glides over rough trails or city streets with unmatched active air-suspension.",
    whyMatch: "The absolute peak of high-status luxury family travel, featuring standard-setting leather interior comfort.",
    badge: "King of SUVs",
    color: "#AB47BC"
  },
  {
    id: "audi-etron",
    name: "Audi e-tron GT Quattro",
    brand: "Audi",
    price: 106500,
    type: "sedan",
    fuel: "electric",
    lifestyle: "eco",
    priority: "luxury",
    specs: {
      range: "249 miles (EPA)",
      acceleration: "3.9s",
      horsepower: "522 hp",
      safety: "5-Star Rating",
      seats: 5,
      cargo: "9.2 cu ft"
    },
    description: "A breathtaking electric grand tourer merging majestic styling proportions, immersive speed, and German craft.",
    whyMatch: "Combines zero-emission luxury with head-turning low-slung futuristic design and high-speed electric charging.",
    badge: "Electric Masterpiece",
    color: "#7E57C2"
  },
  {
    id: "ford-lightning",
    name: "Ford F-150 Lightning AWD",
    brand: "Ford",
    price: 49995,
    type: "truck",
    fuel: "electric",
    lifestyle: "adventure",
    priority: "tech",
    specs: {
      range: "240 - 320 miles",
      acceleration: "4.1s",
      horsepower: "580 hp",
      safety: "5-Star NHTSA",
      seats: 5,
      cargo: "52.8 cu ft bed"
    },
    description: "An electric reimagining of America's workhorse. Features a massive cargo front trunk (frunk) and emergency home backup power.",
    whyMatch: "Perfect for active outdoor off-roading, towing, or utility needs with top-tier battery backup and storage capabilities.",
    badge: "Ultimate Utility",
    color: "#66BB6A"
  },
  {
    id: "mini-cooper-se",
    name: "Mini Cooper SE Electric",
    brand: "Mini",
    price: 30900,
    type: "hatchback",
    fuel: "electric",
    lifestyle: "commute",
    priority: "tech",
    specs: {
      range: "114 miles (EPA)",
      acceleration: "6.9s",
      horsepower: "181 hp",
      safety: "4-Star Rating",
      seats: 4,
      cargo: "8.7 cu ft"
    },
    description: "Classic go-kart handling scaled into an agile, highly customizable, and extremely fun electric city commuter.",
    whyMatch: "Perfect for quick urban navigation, easy street parking, and highly efficient short commutes on pure electricity.",
    badge: "Urban Go-Kart",
    color: "#26C6DA"
  }
];
